server:
  port: 8081
spring:
  application:
    name: emd
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.18:3307/demo?characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
      type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #InnoDB才能支持事务
    hibernate:
        ddl-auto: update
    show-sql: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3600ms
    lettuce:
        pool:
           max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
           max-wait: -1ms
    # 连接池中的最大空闲连接
           max-idle: 1000
    # 连接池中的最小空闲连接
           min-idle: 0
